services:
  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8091:80"
    networks:
      - network
    depends_on:
      - keycloak
      - openbao
      - backend

  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: secretmanager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    networks:
      - network

  frontend:
    build:
      context: ./frontend/
    networks:
      - network

  backend:
    build:
      context: ./backend/
    environment:
      PORT: '8000'
      DATABASE_DSN: 'host=postgres user=admin password=admin dbname=secretmanager port=5432 sslmode=disable'
      AUTH_REALM_URL: "http://keycloak:8080/realms/secretmanager"
      AUTH_CLIENT_ID: "backend"
      AUTH_CLIENT_SECRET: "qSjlRfGamv70qVfNmkangXBaJ6BBZMn0"
    networks:
      - network
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: 'admin'
      KC_BOOTSTRAP_ADMIN_PASSWORD: 'admin'
    networks:
      - network
    volumes:
      - ./keycloak/secretmanager-realm.json:/opt/keycloak/data/import/secretmanager-realm.json
    ports:
      - "8090:8080"
    command:
      - start
      - --import-realm
      - --http-enabled
      - 'true'
      - --hostname-strict
      - 'false'

  openbao:
    image: ghcr.io/openbao/openbao:2.4.1
    volumes:
      - ./openbao/config.hcl:/openbao/config/config.hcl
    networks:
      - network

volumes:
  postgres_db_data:

networks:
  network:
    driver: bridge
