services:
  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8091:80"
    networks:
      - network
    depends_on:
      backend:
        condition: service_started
      openbao:
        condition: service_healthy

  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: secretmanager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    networks:
      - network

  frontend:
    build:
      context: ./frontend/
    networks:
      - network

  backend:
    build:
      context: ./backend/
    environment:
      PORT: '8000'
      DATABASE_DSN: 'host=postgres user=admin password=admin dbname=secretmanager port=5432 sslmode=disable'
      AUTH_REALM_URL: "${KEYCLOAK_PUBLIC_URL:-https://kc.airblo.ws/}realms/secretmanager"
      AUTH_CLIENT_ID: "secretmanager"
      AUTH_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET:-HZ7KVvK2qtecvr0YwC8fmFbFDFEzK9iY}
      OPENBAO_USERNAME: "backend"
      OPENBAO_PASSWORD: ${OPENBAO_PASSWORD:-S0Z19QMNIovOj10B9v5Lwb9sPOXT1Xai}
    networks:
      - network
    depends_on:
      postgres:
        condition: service_started

  openbao:
    image: ghcr.io/openbao/openbao:2.4.1
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    volumes:
      - ./openbao/entrypoint.sh:/entrypoint.sh
      - ./openbao/config.hcl:/openbao/config/config.hcl
      - openbao_data:/openbao/file/
    networks:
      - network
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- http://127.0.0.1:8200/v1/sys/health?standbyok=true >/dev/null"]
      interval: 1s
      timeout: 10s
      retries: 50

volumes:
  postgres_db_data:
  openbao_data:
  keycloak_data:

networks:
  network:
    driver: bridge
