services:
  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8091:80"
    networks:
      - network
    depends_on:
      keycloak:
        condition: service_healthy
      backend:
        condition: service_started
      openbao:
        condition: service_healthy

  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: secretmanager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    networks:
      - network

  frontend:
    build:
      context: ./frontend/
    networks:
      - network

  backend:
    build:
      context: ./backend/
    environment:
      PORT: '8000'
      DATABASE_DSN: 'host=postgres user=admin password=admin dbname=secretmanager port=5432 sslmode=disable'
      AUTH_REALM_URL: "http://keycloak:8080/realms/secretmanager"
      AUTH_CLIENT_ID: "secretmanager"
      AUTH_CLIENT_SECRET: "HZ7KVvK2qtecvr0YwC8fmFbFDFEzK9iY"
    networks:
      - network
    depends_on:
      keycloak:
        condition: service_healthy
      postgres:
        condition: service_started

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_HEALTH_ENABLED: true
    networks:
      - network
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/secretmanager-realm.json:/opt/keycloak/data/import/secretmanager-realm.json
    ports:
      - "8090:8080"
    command:
      - start-dev
      - --import-realm
      - --http-enabled=true
      - --hostname-strict=false
    healthcheck:
      test: ['CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:9000/health/live']
      interval: 1s
      timeout: 10s
      retries: 10

  openbao:
    image: ghcr.io/openbao/openbao:2.4.1
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    volumes:
      - ./openbao/entrypoint.sh:/entrypoint.sh
      - ./openbao/config.hcl:/openbao/config/config.hcl
      - openbao_data:/openbao/file/
    networks:
      - network
    depends_on:
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- http://127.0.0.1:8200/v1/sys/health?standbyok=true >/dev/null"]
      interval: 1s
      timeout: 10s
      retries: 10

volumes:
  postgres_db_data:
  openbao_data:
  keycloak_data:

networks:
  network:
    driver: bridge
