version: '3.8'
services:
  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - network
    depends_on:
      - keycloak
      - openBao
      - backend-main

  postgres-db:
    image: postgres:18
    environment:
      POSTGRES_DB: 'backend'
      POSTGRES_USER: 'backend-user'
      POSTGRES_PASSWORD: 'backend-password'
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    networks:
      - network

  frontend-main:
    image: cr.selcloud.ru/oren2025/frontend:latest
    networks:
      - network

  backend-main:
    image: cr.selcloud.ru/oren2025/backend:latest
    environment:
      PORT: '8000'
      DATABASE_DSN: 'host=postgres-db user=backend-user password=backend-password dbname=backend port=5432 sslmode=disable'
      AUTH_REALM_URL: "http://keycloak:8080/realms/test"
      AUTH_CLIENT_ID: "backend"
      AUTH_CLIENT_SECRET: "HZ7KVvK2qtecvr0YwC8fmFbFDFEzK9iY"
      AUTH_REDIRECT_URL: "http://localhost:3000/auth"
    networks:
      - network
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: 'admin'
      KC_BOOTSTRAP_ADMIN_PASSWORD: 'admin'
    networks:
      - network
    volumes:
      - ./realm-keycloak.json:/opt/keycloak/data/import/realm-export.json
    command:
      - start-dev
      - --import-realm
  
  openBao:
    image: openbao/openbao
    environment:
      BAO_DEV_ROOT_TOKEN_ID: 'foobar'
    networks:
      - network

volumes:
  postgres_db_data:

networks:
  network:
    driver: bridge
