name: Build docker

on:
  workflow_dispatch:

env:
  REGISTRY: cr.selcloud.ru

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: token
        password: ${{secrets.SELECTEL_TOKEN}}

    - uses: docker/build-push-action@master
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/oren2025/${{ github.ref_name }}:${{ github.sha }}
          ${{ env.REGISTRY }}/oren2025/${{ github.ref_name }}:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache,mode=max